# Generated by Django 2.2 on 2020-09-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
